### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by ilsma** [strapi/strapi-tutorials#17]
`<script>  
import articlesQuery from '~/apollo/queries/article/articles'

export default {  
  props: {
    articles: Array
  },
  computed: {
    leftArticlesCount(){
      return Math.ceil(this.articles.length / 5)
    },
    leftArticles(){
      return this.articles.slice(0,this.leftArticlesCount)
    },
    rightArticles(){
      return this.articles.slice(this.leftArticlesCount, this.articles.length)
    }
  }
}
</script>  `

**Comment by lauriejim** [comment]
Hello @ilsma !

Can you please well format your code using [Markdown](https://guides.github.com/features/mastering-markdown/) syntax.
This will help us to better read your code.

After that, can you give more details because your issue is not understandable.

I close it - will reopen it when you will have updated it.

Thank you.

**Comment by jmalley** [comment]
@ilsma Did you ever figure this out? I'm having a problem with the same piece of code, except for me it's saying that "this.articles is undefined."

`Invalid prop: type check failed for prop "articles". Expected Array, got Undefined `
