### ISSUE TITLE
[UPDATE OUTDATED CONTENT]

### ISSUE THREAD

**Issue by ep0ll** [strapi/strapi-tutorials#937]
**Description**

**Link of the content** : https://strapi.io/blog/how-to-run-a-strapi-dev-stack-with-docker-compose

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by EzzEddin** [comment]
Hi @dessireugarte! I have already walked through the content and also played around with docker compose for strapi and MySQL services. Ran `docker-compose up -d` and here is the Strapi admin UI:
![strapi_admin_ui](https://user-images.githubusercontent.com/11898152/185923346-9d2e8dec-2a2f-4c26-ba7d-0c19facf4ed8.png)
)

My question is: do you want Strapi version 4 to be included in this post? or version 3.6.8 (because this is the latest version that exists on Strapi Docker hub)?

**Comment by dessireugarte** [comment]
Hello @WYGIN @EzzEddin 👋 
The update of this article would be for the latest version of Strapi v4. 
It would need to be adapted, and I suggest using these resources that are the ones that we are suggesting the community to use: 
- [Docker with Strapi V4](https://blog.dehlin.dev/docker-with-strapi-v4#cl6izyrzb09o6xvnvhheegzt0)
- [strapi-tool-dockerize](https://github.com/strapi-community/strapi-tool-dockerize)

Let me know if any of you is interested in writing it!
